from social.apps.django_app.middleware import SocialAuthExceptionMiddleware
# placate pyflakes
SocialAuthExceptionMiddleware
